import json
import zipfile
from io import BytesIO
from pathlib import Path

from fastapi.responses import JSONResponse, StreamingResponse

from app.db import connect

BASE = Path('.')

META_TEMPLATE = {
    "title": "",
    "description": "",
    "brand": "",
    "size": "",
    "item_type": "",
    "colour": "",
    "price_gbp": None,
    "notes": "Generated by Vinted Pi. Review before posting."
}

def _draft_meta(item_id: int):
    """Return (metadata_dict, photos_rows) for the draft."""
    with connect() as c:
        attrs = {r['field']: r['value'] for r in c.execute(
            'select field,value from attributes where item_id=?', (item_id,))}
        draft = c.execute('select * from drafts where item_id=?',
                          (item_id,)).fetchone()
        photos = c.execute('select * from photos where item_id=?',
                           (item_id,)).fetchall()
        price = c.execute('select * from prices where item_id=?',
                          (item_id,)).fetchone()

    meta = META_TEMPLATE.copy()
    meta["title"] = (draft['title'] or '').strip() if draft else ''

    bits = []
    if attrs.get('brand'):
        bits.append(f"Brand: {attrs['brand']}")
    if attrs.get('size'):
        bits.append(f"Size: {attrs['size']}")
    if attrs.get('item_type'):
        bits.append(f"Type: {attrs['item_type']}")
    if attrs.get('colour'):
        bits.append(f"Colour: {attrs['colour']}")
    meta["description"] = "\n".join(bits)

    meta["brand"] = attrs.get('brand', '')
    meta["size"] = attrs.get('size', '')
    meta["item_type"] = attrs.get('item_type', '')
    meta["colour"] = attrs.get('colour', '')
    if price and price['recommended_pence']:
        meta["price_gbp"] = round(price['recommended_pence']/100, 2)

    return meta, photos

def build_zip_bytes(item_id: int) -> bytes:
    """Create an in-memory ZIP of images + metadata for assistive posting."""
    meta, photos = _draft_meta(item_id)
    mem = BytesIO()
    with zipfile.ZipFile(mem, mode='w', compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('metadata.json', json.dumps(meta, indent=2))
        title = meta.get('title') or f"Vinted Item #{item_id}"
        desc  = meta.get('description', '')
        zf.writestr('title.txt', title)
        zf.writestr('description.txt', desc)
        for p in photos:
            jpg = Path(p['optimised_path'])
            if jpg.exists():
                zf.write(jpg, arcname=f"images/{jpg.name}")
    return mem.getvalue()

def build_listing_pack(item_id: int):
    """FastAPI response that streams the ZIP to the browser."""
    try:
        data = build_zip_bytes(item_id)
        filename = f"vinted-pack-{item_id}.zip"
        return StreamingResponse(
            BytesIO(data),
            media_type='application/zip',
            headers={'Content-Disposition': f'attachment; filename="{filename}"'}
        )
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)
